FROM centos:centos7.4.1708

RUN yum -y install \
	asciidoc \
	audit-libs-devel \
	bc \
	binutils-devel \
	bison \
	cmake \
	elfutils-devel \
	gcc-c++ \
	gettext \
	hmaccalc \
	java-devel \
	m4 \
	make \
        git \
	ncurses-devel \
	net-tools \
	newt-devel \
	numactl-devel \
	openssl \
	openssl-devel \
	pciutils-devel \
	pesign \
	'perl(ExtUtils::Embed)' \
	python-devel \
	python-docutils \
	rpm-build \
	which \
	xmlto \
        wget \
        boost-devel \
	zlib-devel
