#!/bin/bash
set -eu

# regex'ing kernel version from the content of /var/lib/dpkg/info/vcass-modules*.list is unreliable as this file remains even for uninstalled versions of vcass-modules, and contains few enties (e.g. /etc, sometimes even /lib/modules/... ) shared with other packages

# The value of TARGET_KERNEL_VER is necessary for depmod to direct it not to use the version string of
# the currently running kernel as reported by "uname -r".

TARGET_KERNEL_VER="$( basename "$0" )" # expecing basename in the form: vcass-modules-4.19.0-1.2.5.242.vca.postinst
TARGET_KERNEL_VER="${TARGET_KERNEL_VER#"vcass-modules-"}"
TARGET_KERNEL_VER="${TARGET_KERNEL_VER%".postinst"}"

depmod "${TARGET_KERNEL_VER}"
vca_setup.sh

