#!/bin/bash
ln -s /usr/sbin/vcactl /usr/sbin/vcactrl
touch /etc/vca_config.d/config.lock
chmod 660 /etc/vca_config.d/config.lock
chgrp -R vcausers /etc/vca_config.d/
chmod 775 /etc/vca_config.d/
chgrp -R vcausers /usr/lib/vca/
chgrp vcausers /usr/sbin/vca*
chgrp vcausers /etc/profile.d/vca*

if [ -f /etc/vca_config.d/vca_config.old_user.xml ]; then
	cp /etc/vca_config.d/vca_config.xml /etc/vca_config.d/vca_config.new_default.xml
	vca_config_upgrade.sh || echo 'Configuration update failed, this is not fatal error.'
fi

systemctl enable vcactl && systemctl start vcactl
# re-trigger 'add' event in kernel in case VCA kernel modules have already been loaded:
(
	cd /dev
	for NAME in vca* ; do
		udevadm trigger --action=add --type=devices --sysname-match=${NAME}
	done
)
