#
# Makefile - Intel VCA Linux driver.
# Copyright(c) 2015, Intel Corporation.
#
obj-m := vop.o

vop-objs += vop_common.o
vop-objs += vop_kvec_buff.o
vop-objs += vop_main.o
vop-objs += vop_debugfs.o
vop-objs += vop_vringh.o
